version: '3.4'

services:

  discount.database:
    container_name: discount.database
    image: postgres:latest
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: discountDb
    ports:
      - 5432:5432

  catalog.database:
    image: mongo:latest
    container_name: catalog.database
    environment:
     - MONGO_DB=eShopping
     - MONGO_USER=admin
     - MONGO_PASSWORD=12345678 
    volumes:
     - ./mongo/data:/data/db
    ports:
     - 27017:27017

  ordering.database:
    container_name: ordering.database
    hostname: ordering.database
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Admin@12345678'
      MSSQL_DATA_DIR: /var/opt/mssql/data
      MSSQL_PID: 'Developer' 
      MSSQL_TCP_PORT: 1433 
    ports: 
      - "1455:1433"
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets

  basket.cache:
    image: redis:latest
    container_name: basket.cache
    restart: always
    ports:
     - 6379:6379 

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data


  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ASPNETCORE_HTTPS_PORTS=9001
     - ASPNETCORE_HTTP_PORTS=8001
     - ASPNETCORE_Kestrel__Certificates__Default__Password=12345678
     - ASPNETCORE_Kestrel__Certificates__Default__Path=aspnetapp.pfx
    ports:
     - "9001:9001"
     - "8001:8001" 
    build:
      context: .
      dockerfile: Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ASPNETCORE_HTTPS_PORTS=9002
     - ASPNETCORE_HTTP_PORTS=8002
     - ASPNETCORE_Kestrel__Certificates__Default__Password=12345678
     - ASPNETCORE_Kestrel__Certificates__Default__Path=aspnetapp.pfx 
    ports:
     - "9002:9002"
     - "8002:8002" 
    build:
      context: .
      dockerfile: Basket.API/Dockerfile

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ASPNETCORE_HTTPS_PORTS=5001
     - ASPNETCORE_HTTP_PORTS=8003
     - ASPNETCORE_Kestrel__Certificates__Default__Password=12345678
     - ASPNETCORE_Kestrel__Certificates__Default__Path=aspnetapp.pfx 
    ports:
     - "5001:5001"
     - "8003:8003" 
    build:
      context: .
      dockerfile: Discount.API/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ASPNETCORE_HTTPS_PORTS=9004
     - ASPNETCORE_HTTP_PORTS=8004
     - ASPNETCORE_Kestrel__Certificates__Default__Password=12345678
     - ASPNETCORE_Kestrel__Certificates__Default__Path=aspnetapp.pfx 
    ports:
     - "9004:9004"
     - "8004:8004" 
    build:
      context: .
      dockerfile: Ordering.API/Dockerfile


volumes:
  portainer_data: