version: '3.4'

services:

  discount.database:
    container_name: discount.database
    image: postgres:latest
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: discountDb
    ports:
      - 5432:5432
    networks:
      - eshopproxybackend

  catalog.database:
    image: mongo:latest
    container_name: catalog.database
    environment:
     - MONGO_DB=eShopping
     - MONGO_USER=admin
     - MONGO_PASSWORD=12345678 
    volumes:
     - ./mongo/data:/data/db
    ports:
     - 27017:27017
    networks:
      - eshopproxybackend

  ordering.database:
    container_name: ordering.database
    hostname: ordering.database
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Admin@12345678'
      MSSQL_DATA_DIR: /var/opt/mssql/data
      MSSQL_PID: 'Developer' 
      MSSQL_TCP_PORT: 1433 
    ports: 
      - "1433:1433"
    volumes:
      - ./datamain:/var/opt/mssql/data
      - ./logmain:/var/opt/mssql/log
      - ./secretsmain:/var/opt/mssql/secrets
    networks:
      - eshopproxybackend

  users.database:
    image: mysql:latest
    container_name: users.database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: eshopping
      MYSQL_USER: eshop_admin
      MYSQL_PASSWORD: eshop_admin_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - eshopproxybackend

  basket.cache:
    image: redis:latest
    container_name: basket.cache
    restart: always
    ports:
     - 6379:6379 
    networks:
      - eshopproxybackend

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - eshopproxybackend

  eshopping.rabbitmq:
    image: rabbitmq:3-management
    container_name: eshopping.rabbitmq
    ports:
      - "5672:5672"  # Default RabbitMQ port
      - "15672:15672"  # Management console port
    environment:
      RABBITMQ_DEFAULT_USER: eshopping
      RABBITMQ_DEFAULT_PASS: echo@@123Titan
    networks:
      - eshopproxybackend

  gateway.api:
    image: ${DOCKER_REGISTRY-}gatwayapi
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ASPNETCORE_HTTPS_PORTS=8081
     - ASPNETCORE_HTTP_PORTS=8080
     - ASPNETCORE_Kestrel__Certificates__Default__Password=12345678
     - ASPNETCORE_Kestrel__Certificates__Default__Path=aspnetapp.pfx
    ports:
     - "8081:8081"
     - "8080:8080" 
    build:
      context: .
      dockerfile: Gateway/Gateway.API/Dockerfile
    networks:
      - eshopproxybackend

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ASPNETCORE_HTTPS_PORTS=9001
     - ASPNETCORE_HTTP_PORTS=8001
     - ASPNETCORE_Kestrel__Certificates__Default__Password=12345678
     - ASPNETCORE_Kestrel__Certificates__Default__Path=aspnetapp.pfx
    ports:
     - "9001:9001"
     - "8001:8001" 
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    networks:
      - eshopproxybackend

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTPS_PORTS: 9002
      ASPNETCORE_HTTP_PORTS: 8002
      ASPNETCORE_Kestrel__Certificates__Default__Password: 12345678
      ASPNETCORE_Kestrel__Certificates__Default__Path: aspnetapp.pfx 
      RABBITMQ_HOST: eshopping.rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: eshopping
      RABBITMQ_PASSWORD: echo@@123Titan
    ports:
     - "9002:9002"
     - "8002:8002" 
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    depends_on:
      - eshopping.rabbitmq
    networks:
      - eshopproxybackend

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ASPNETCORE_HTTPS_PORTS=5001
     - ASPNETCORE_HTTP_PORTS=8003
     - ASPNETCORE_Kestrel__Certificates__Default__Password=12345678
     - ASPNETCORE_Kestrel__Certificates__Default__Path=aspnetapp.pfx 
    ports:
     - "5001:5001"
     - "8003:8003" 
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile
    networks:
      - eshopproxybackend

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTPS_PORTS: 9004
      ASPNETCORE_HTTP_PORTS: 8004
      ASPNETCORE_Kestrel__Certificates__Default__Password: 12345678
      ASPNETCORE_Kestrel__Certificates__Default__Path: aspnetapp.pfx 
      RABBITMQ_HOST: eshopping.rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: eshopping
      RABBITMQ_PASSWORD: echo@@123Titan
    ports:
     - "9004:9004"
     - "8004:8004" 
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile
    depends_on:
      - eshopping.rabbitmq
    networks:
      - eshopproxybackend

  users.api:
    image: ${DOCKER_REGISTRY-}usersapi
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ASPNETCORE_HTTPS_PORTS=9005
     - ASPNETCORE_HTTP_PORTS=8005
     - ASPNETCORE_Kestrel__Certificates__Default__Password=12345678
     - ASPNETCORE_Kestrel__Certificates__Default__Path=aspnetapp.pfx 
    ports:
     - "9005:9005"
     - "8005:8005" 
    build:
      context: .
      dockerfile: Services/Users/Users.API/Dockerfile
    networks:
      - eshopproxybackend

networks:
  eshopproxybackend:
    name: eshopproxybackend
    driver: bridge

volumes:
  portainer_data:
  mysql_data:

